# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DEyge1wv-0c49cz7zLNr-6VhHJfaaqZm
"""

!pip install requests beautifulsoup4 openai langchain-openai

import requests
from bs4 import BeautifulSoup
from langchain_openai.chat_models.azure import AzureChatOpenAI


def extract_text_from_url(url):
    try:
        response = requests.get(url)
        response.raise_for_status()  # Verifica se a requisição foi bem-sucedida

        soup = BeautifulSoup(response.text, 'html.parser')
        for script_or_style in soup(["script", "style"]):
            script_or_style.decompose()  # Remove JavaScript e CSS

        texto = soup.get_text(separator=' ')
        linhas = (line.strip() for line in texto.splitlines())
        parts = (phrase.strip() for line in linhas for phrase in line.split('  '))
        texto_limpo = '\n'.join(part for part in parts if part)
        return texto_limpo
    except Exception as e:
        print(f"Erro ao extrair texto da URL: {e}")
        return None



        extract_text_from_url('https://dev.to/jeffsalive/why-are-we-still-learning-in-2d-when-the-world-is-3d-hcd')

client = AzureChatOpenAI(
    azure_endpoint='https://ai-dio-bootcamp-dev-eastus-001.openai.azure.com/',
    api_key="60Q0MJuBhMl3mUVbNqKLP6QXhA0RuxwdsYcAeid2gYFwvn68luD3JQQJ99AKACHYHv6XJ3w3AAABACOG0vZG",
    api_version="turbo-2024-04-09",
    deployment_name="gpt-4",
    max_retries=0
)
def translate_article(text, lang):
    try:
        messages = [
            {"role": "system", "content": "Você atua como tradutor de texto."},
            {"role": "user", "content": f"Traduza o seguinte texto para {lang}:\n\n{text}"}
        ]
        # Passa as mensagens no formato esperado
        response = client.invoke(input=messages)
        return response['choices'][0]['message']['content']  # Extração do conteúdo traduzido
    except Exception as e:
        print(f"Erro ao traduzir o texto: {e}")
        return None

url = "https://dev.to/jeffsalive/why-are-we-still-learning-in-2d-when-the-world-is-3d-hcd"

# Extração e tradução
texto_extraido = extract_text_from_url(url)
if texto_extraido:
    artigo_traduzido = translate_article(texto_extraido, "pt-br")
    if artigo_traduzido:
        print(artigo_traduzido)
    else:
        print("Erro ao traduzir o texto.")
else:
    print("Erro ao extrair texto da URL.")